<?php
/*
define("DB_HOST","localhost");
define("DB_NAME","aokhoacd_shop");
define("DB_USER","aokhoacd_thanghoang");
define("DB_PWD","Hoangthang123");
*/
define("DB_HOST","localhost");
define("DB_NAME","cedu");
define("DB_USER","root");
define("DB_PWD","root");
?>
